version: '3.8'

services:
  postgres-primary:
    image: postgres:16
    container_name: postgres_primary
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bancodb
    ports:
      - "5440:5432"
    volumes:
      - ./primary/data:/var/lib/postgresql/data
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - replication-network
    command: >
      postgres -c 'wal_level=replica'
               -c 'max_wal_senders=3'
               -c 'wal_keep_size=128MB'

  postgres-replica1:
    image: postgres:16
    container_name: postgres_replica1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bancodb
    ports:
      - "5433:5432"
    volumes:
      - ./replica1/data:/var/lib/postgresql/data
    networks:
      - replication-network
    depends_on:
      - postgres-primary

  postgres-replica2:
    image: postgres:16
    container_name: postgres_replica2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bancodb
    ports:
      - "5434:5432"
    volumes:
      - ./replica2/data:/var/lib/postgresql/data
    networks:
      - replication-network
    depends_on:
      - postgres-primary

networks:
  replication-network:
    driver: bridge