version: '3.8'

services:
  citus-coord:
    image: citusdata/citus:latest
    container_name: citus_coordinador
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    networks:
      - citus-network

  citus-worker1:
    image: citusdata/citus:latest
    container_name: citus_worker1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5436:5432"
    networks:
      - citus-network

  citus-worker2:
    image: citusdata/citus:latest
    container_name: citus_worker2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5437:5432"
    networks:
      - citus-network

networks:
  citus-network:
    driver: bridge